services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chaindegree-sql

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

    ports:
      - "${MSSQL_PORT}:1433"

    volumes:
      - ./docker/mssql/data:/var/opt/mssql/data

    restart: unless-stopped