<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChainDegree.Domain\ChainDegree.Core.Domain.csproj" />
    <ProjectReference Include="..\ChainDegree.SharedKernel\ChainDegree.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Applications\Commands\SubmitApplication\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Messaging\" />
    <Folder Include="Degrees\Commands\UpdateDegree\" />
    <Folder Include="Degrees\Commands\RevokeDegree\" />
    <Folder Include="Degrees\Queries\GetDegreeById\" />
    <Folder Include="Degrees\Queries\VerifyDegree\" />
    <Folder Include="Jobs\Commands\CreateJob\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0-preview.1.25080.5" />
  </ItemGroup>

</Project>
