<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChainDegree.Application\ChainDegree.Core.Application.csproj" />
    <ProjectReference Include="..\ChainDegree.Domain\ChainDegree.Core.Domain.csproj" />
    <ProjectReference Include="..\ChainDegree.SharedKernel\ChainDegree.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Blockchain\Services\" />
    <Folder Include="Persistence\Configurations\" />
    <Folder Include="Persistence\Outbox\" />
    <Folder Include="Persistence\Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
    <PackageReference Include="Nethereum.Web3" Version="6.1.0" />
  </ItemGroup>

</Project>
